export const categories = {
  'estilo-de-vida': { label: 'Estilo de vida', color: '#16a34a', slug: 'estilo-de-vida' },
  'desarrollo-personal': { label: 'Desarrollo personal', color: '#6366f1', slug: 'desarrollo-personal' },
  'masculinidad': { label: 'Masculinidad', color: '#ea580c', slug: 'masculinidad' },
  'fitness': { label: 'Fitness', color: '#22c55e', slug: 'fitness' },
  'nutricion': { label: 'Nutrición', color: '#f59e0b', slug: 'nutricion' },
  'habitos-saludables': { label: 'Hábitos saludables', color: '#4ade80', slug: 'habitos-saludables' },
  'productividad': { label: 'Productividad', color: '#2563eb', slug: 'productividad' },
  'inversion': { label: 'Inversión', color: '#d97706', slug: 'inversion' },
  'analisis-tecnico': { label: 'Análisis técnico', color: '#0e7490', slug: 'analisis-tecnico' },
  'criptomonedas': { label: 'Criptomonedas', color: '#f97316', slug: 'criptomonedas' },
  'impuestos': { label: 'Impuestos', color: '#ca8a04', slug: 'impuestos' },
  'dinero': { label: 'Dinero', color: '#15803d', slug: 'dinero' },
  'relaciones': { label: 'Relaciones', color: '#be185d', slug: 'relaciones' },
  'seduccion': { label: 'Seducción', color: '#dc2626', slug: 'seduccion' },
  'estilo': { label: 'Estilo', color: '#a855f7', slug: 'estilo' },
  'mitos-nutricionales': { label: 'Mitos nutricionales', color: '#f43f5e', slug: 'mitos-nutricionales' },
  'relaciones-de-pareja': { label: 'Relaciones de pareja', color: '#db2777', slug: 'relaciones-de-pareja' },
  'bitcoin': { label: 'Bitcoin', color: '#f97316', slug: 'bitcoin' },
  'habilidades-sociales': { label: 'Habilidades sociales', color: '#0ea5e9', slug: 'habilidades-sociales' },
  'mundo': { label: 'Mundo', color: '#0f766e', slug: 'mundo' },
  'antiveganismo': { label: 'Antiveganismo', color: '#991b1b', slug: 'antiveganismo' },
  'radiaciones-electromagn': { label: 'Radiaciones electromagnéticas', color: '#9333ea', slug: 'radiaciones-electromagn' },
  'negocios': { label: 'Negocios', color: '#047857', slug: 'negocios' },
  'enigmas-de-la-historia': { label: 'Enigmas de la historia', color: '#7e22ce', slug: 'enigmas-de-la-historia' },
  'ejercicios-empuje-horizontal': { label: 'Ejercicios de empuje horizontal', color: '#f87171', slug: 'ejercicios-empuje-horizontal' },
  'ejercicios-empuje-vertical': { label: 'Ejercicios de empuje vertical', color: '#fb923c', slug: 'ejercicios-empuje-vertical' },
  'minimalismo': { label: 'Minimalismo', color: '#6b7280', slug: 'minimalismo' },
} as const
