// This file is generated by the scraper task
export const categories = [
  {
    slug: 'estilo-de-vida',
    label: 'Estilo de vida',
    color: '#16a34a',
  },
  {
    slug: 'desarrollo-personal',
    label: 'Desarrollo personal',
    color: '#6366f1',
  },
  {
    slug: 'masculinidad',
    label: 'Masculinidad',
    color: '#ea580c',
  },
  {
    slug: 'fitness',
    label: 'Fitness',
    color: '#22c55e',
  },
  {
    slug: 'nutricion',
    label: 'Nutrición',
    color: '#f59e0b',
  },
  {
    slug: 'habitos-saludables',
    label: 'Hábitos saludables',
    color: '#4ade80',
  },
  {
    slug: 'productividad',
    label: 'Productividad',
    color: '#2563eb',
  },
  {
    slug: 'inversion',
    label: 'Inversión',
    color: '#d97706',
  },
  {
    slug: 'analisis-tecnico',
    label: 'Análisis técnico',
    color: '#0e7490',
  },
  {
    slug: 'criptomonedas',
    label: 'Criptomonedas',
    color: '#f97316',
  },
  {
    slug: 'impuestos',
    label: 'Impuestos',
    color: '#ca8a04',
  },
  {
    slug: 'dinero',
    label: 'Dinero',
    color: '#15803d',
  },
  {
    slug: 'relaciones',
    label: 'Relaciones',
    color: '#be185d',
  },
  {
    slug: 'seduccion',
    label: 'Seducción',
    color: '#dc2626',
  },
  {
    slug: 'estilo',
    label: 'Estilo',
    color: '#a855f7',
  },
  {
    slug: 'mitos-nutricionales',
    label: 'Mentiras nutricionales',
    color: '#f43f5e',
  },
  {
    slug: 'relaciones-de-pareja',
    label: 'Relaciones de pareja',
    color: '#db2777',
  },
  {
    slug: 'bitcoin',
    label: 'Bitcoin',
    color: '#f97316',
  },
  {
    slug: 'habilidades-sociales',
    label: 'Habilidades sociales',
    color: '#0ea5e9',
  },
  {
    slug: 'mundo',
    label: 'Mundo',
    color: '#0f766e',
  },
  {
    slug: 'antiveganismo',
    label: 'Antiveganismo',
    color: '#991b1b',
  },
  {
    slug: 'radiaciones-electromagn',
    label: 'Radiaciones electromagnéticas',
    color: '#9333ea',
  },
  {
    slug: 'negocios',
    label: 'Negocios',
    color: '#047857',
  },
  {
    slug: 'enigmas-de-la-historia',
    label: 'Enigmas de la historia',
    color: '#7e22ce',
  },
  {
    slug: 'ejercicios-empuje-horizontal',
    label: 'Ejercicios empuje horizontal',
    color: '#f87171',
  },
  {
    slug: 'ejercicios-empuje-vertical',
    label: 'Ejercicios empuje vertical',
    color: '#fb923c',
  },
  {
    slug: 'minimalismo',
    label: 'Minimalismo',
    color: '#6b7280',
  },
]
